(function() {
  module.exports = {
    sex: [
      {code: 'male', name: '男'},
      {code: 'famale', name: '女'}
    ],

    degree_of_education: [
      { code: '1', name: '博士' },
      { code: '2', name: '硕士' },
      { code: '3', name: '本科' },
      { code: '4', name: '大专(专科)' },
      { code: '5', name: '高中(职高)' },
      { code: '6', name: '中专(中技)' },
      { code: '7', name: '初中' },
      { code: '8', name: '初中以下' }
    ],

    id_type: [
      { code: '1', name: '中华人民共和国居民身份证' },
      { code: '2', name: '台湾居民往来大陆通行证' },
      { code: '3', name: '港澳居民来往内地通行证' },
      { code: '4', name: '军人证件' },
      { code: '5', name: '护照' }
    ],

    nationality: [
      { code: '01', name: '汉' },
      { code: '10', name: '朝鲜' },
      { code: '11', name: '满' },
      { code: '12', name: '侗' },
      { code: '13', name: '瑶' },
      { code: '14', name: '白' },
      { code: '15', name: '土家' },
      { code: '16', name: '哈尼' },
      { code: '17', name: '哈萨克' },
      { code: '18', name: '傣' },
      { code: '19', name: '黎' },
      { code: '20', name: '傈僳' },
      { code: '21', name: '佤' },
      { code: '22', name: '畲' },
      { code: '23', name: '高山' },
      { code: '24', name: '拉祜' },
      { code: '25', name: '水' },
      { code: '26', name: '东乡' },
      { code: '27', name: '纳西' },
      { code: '28', name: '景颇' },
      { code: '29', name: '柯尔克孜' },
      { code: '30', name: '土' },
      { code: '31', name: '达斡尔' },
      { code: '32', name: '仫佬' },
      { code: '33', name: '羌' },
      { code: '34', name: '布朗' },
      { code: '35', name: '撒拉' },
      { code: '36', name: '毛难' },
      { code: '37', name: '仡佬' },
      { code: '38', name: '锡伯' },
      { code: '39', name: '阿昌' },
      { code: '40', name: '普米' },
      { code: '41', name: '塔吉克' },
      { code: '42', name: '怒' },
      { code: '43', name: '乌孜别克' },
      { code: '44', name: '俄罗斯' },
      { code: '45', name: '鄂温克' },
      { code: '46', name: '德昂' },
      { code: '47', name: '保安' },
      { code: '48', name: '裕固' },
      { code: '49', name: '京' },
      { code: '50', name: '塔塔尔' },
      { code: '51', name: '独龙' },
      { code: '52', name: '鄂伦春' },
      { code: '53', name: '赫哲' },
      { code: '54', name: '门巴' },
      { code: '55', name: '珞巴' },
      { code: '56', name: '基诺' },
      { code: '97', name: '其他' },
      { code: '98', name: '外国血统' },
      { code: '02', name: '蒙古' },
      { code: '03', name: '回' },
      { code: '04', name: '藏' },
      { code: '05', name: '维吾尔' },
      { code: '06', name: '苗' },
      { code: '07', name: '彝' },
      { code: '08', name: '壮' },
      { code: '09', name: '布依' }
    ]
    ,

    career: [
      { code: '30', name: '学生' },
      { code: '10', name: '失业（含待业及无业人员）' },
      { code: '11', name: '科学研究人员' },
      { code: '13', name: '工程技术人员' },
      { code: '17', name: '农业技术人员' },
      { code: '18', name: '飞机和船舶技术人员' },
      { code: '19', name: '卫生专业技术人员' },
      { code: '21', name: '经济业务人员' },
      { code: '22', name: '金融业务人员' },
      { code: '23', name: '法律专业人员' },
      { code: '24', name: '教学人员' },
      { code: '25', name: '文学艺术工作人员' },
      { code: '26', name: '体育工作人员' },
      { code: '27', name: '新闻出版、文化工作人员' },
      { code: '28', name: '宗教职业者' },
      { code: '29', name: '其他专业技术人员' },
      { code: '31', name: '行政办公人员' },
      { code: '32', name: '安全保卫和消防人员' },
      { code: '33', name: '邮政和电信业务人员' },
      { code: '39', name: '其他办事人员和有关人员' },
      { code: '41', name: '购销人员' },
      { code: '42', name: '仓储人员' },
      { code: '43', name: '餐饮服务人员' },
      { code: '44', name: '饭店、旅游及健身娱乐场所服务人员' },
      { code: '45', name: '运输服务人员' },
      { code: '46', name: '医疗卫生辅助服务人员' },
      { code: '47', name: '社会服务和居民生活服务人员' },
      { code: '49', name: '其他商业、服务业人员' },
      { code: '51', name: '种植业生产人员' },
      { code: '52', name: '林业生产及野生动植物保护人员' },
      { code: '53', name: '畜牧业生产人员' },
      { code: '54', name: '渔业生产人员' },
      { code: '55', name: '水利设施管理养护人员' },
      { code: '59', name: '其他农、林、牧、渔、水利业生产人员' },
      { code: '61', name: '勘测及矿物开采人员' },
      { code: '62', name: '金属冶炼、轧制人员' },
      { code: '64', name: '化工产品生产人员' },
      { code: '66', name: '机械制造加工人员' },
      { code: '67', name: '机电产品装配人员' },
      { code: '71', name: '机械设备修理人员' },
      { code: '72', name: '电力设备安装、运行、检修及供电人员' },
      { code: '73', name: '电子元器件与设备制造、装配、调试及维修人员' },
      { code: '74', name: '橡胶和塑料制品生产人员' },
      { code: '75', name: '纺织、针织、印染人员' },
      { code: '76', name: '裁剪、缝纫和皮革、毛皮制品加工制作人员' },
      { code: '77', name: '粮油、食品、饮料生产加工及饲料生产加工人员' },
      { code: '78', name: '烟草及其制品加工人员' },
      { code: '79', name: '药品生产人员' },
      { code: '81', name: '木材加工、人造板生产、木制品制作及制浆、造纸和纸制品生产加工人员' },
      { code: '82', name: '建筑材料生产加工人员' },
      { code: '83', name: '玻璃、陶瓷、搪瓷及其制品生产加工人员' },
      { code: '84', name: '广播影视制品制作、播放及文物保护作业人员' },
      { code: '85', name: '印刷人员' },
      { code: '86', name: '工艺、美术品制作人员' },
      { code: '87', name: '文化教育、体育用品制作人员' },
      { code: '88', name: '工程施工人员' },
      { code: '91', name: '运输设备操作人员及有关人员' },
      { code: '92', name: '环境监测与废物处理人员' },
      { code: '93', name: '检验、计量人员' },
      { code: '99', name: '其他生产、运输设备操作人员及有关人员' },
      { code: '01', name: '中国共产党中央委员会和地方各级组织负责人' },
      { code: '02', name: '国家机关及其工作机构负责人' },
      { code: '03', name: '民主党派和社会团体及其工作机构负责人' },
      { code: '04', name: '事业单位负责人' },
      { code: '05', name: '企业负责人' },
      { code: '08', name: '军人' },
      { code: '09', name: '不便分类的其他从业人员' }
    ],

    department: [
      { code: '10', name: '数信' },
      { code: '11', name: '法学' },
      { code: '43', name: '国教' },
      { code: '45', name: '建筑' },
      { code: '49', name: '软件' },
      { code: '01', name: '资环' },
      { code: '02', name: '水利' },
      { code: '03', name: '土木' },
      { code: '04', name: '机械' },
      { code: '05', name: '电力' },
      { code: '06', name: '环工' },
      { code: '07', name: '管经' },
      { code: '08', name: '信工' },
      { code: '09', name: '外语' }
    ],
    school: [
      { code: '10', name: '河南中医学院' },
      { code: '11', name: '郑州航空工业管理学院' },
      { code: '12', name: '河南工程学院' },
      { code: '13', name: '河南警察学院' },
      { code: '14', name: '黄河科技学院' },
      { code: '15', name: '郑州科技学院' },
      { code: '16', name: '郑州华信学院' },
      { code: '17', name: '郑州师范学院' },
      { code: '18', name: '郑州成功财经学院' },
      { code: '19', name: '郑州升达经贸管理学院' },
      { code: '20', name: '河南财政税务高等专科学校' },
      { code: '21', name: '郑州电力高等专科学校' },
      { code: '22', name: '郑州幼儿师范高等专科学校' },
      { code: '23', name: '河南医学高等专科学校' },
      { code: '24', name: '郑州澍青医学高等专科学校' },
      { code: '25', name: '河南职业技术学院' },
      { code: '26', name: '郑州铁路职业技术学院' },
      { code: '27', name: '中州大学' },
      { code: '28', name: '河南水利与环境职业学院' },
      { code: '29', name: '河南信息统计职业学院' },
      { code: '30', name: '郑州电力职业技术学院' },
      { code: '31', name: '河南建筑职业技术学院' },
      { code: '32', name: '郑州城市职业学院' },
      { code: '33', name: '郑州理工职业学院' },
      { code: '34', name: '郑州信息工程职业学院' },
      { code: '35', name: '河南艺术职业学院' },
      { code: '37', name: '河南机电职业学院' },
      { code: '38', name: '郑州商贸旅游职业学院' },
      { code: '39', name: '郑州黄河护理职业学院' },
      { code: '40', name: '郑州财税金融职业学院' },
      { code: '41', name: '河南司法警官职业学院' },
      { code: '42', name: '郑州经贸职业学院' },
      { code: '43', name: '郑州交通职业学院' },
      { code: '44', name: '河南检察职业学院' },
      { code: '45', name: '郑州信息科技职业学院' },
      { code: '46', name: '郑州电子信息职业技术学院' },
      { code: '47', name: '嵩山少林武术职业学院' },
      { code: '48', name: '郑州工业安全职业学院' },
      { code: '49', name: '河南经贸职业学院' },
      { code: '50', name: '河南交通职业技术学院' },
      { code: '51', name: '河南农业职业学院' },
      { code: '52', name: '郑州旅游职业学院' },
      { code: '53', name: '郑州职业技术学院' },
      { code: '54', name: '河南工业贸易职业学院' },
      { code: '01', name: '其他学校或工作单位' },
      { code: '02', name: '郑州大学' },
      { code: '03', name: '河南工业大学' },
      { code: '04', name: '河南农业大学' },
      { code: '05', name: '河南财经政法大学' },
      { code: '06', name: '铁道警察学院' },
      { code: '07', name: '郑州轻工业学院' },
      { code: '08', name: '中原工学院' },
      { code: '09', name: '河南牧业经济学院' }
    ],

    training_type: [
      { code: '1', name: '在校正规课程社会培训班' },
      { code: '2', name: '社会培训班' },
      { code: '3', name: '未参加培训' }
    ],

    //在信息查询页面显示的信息结构
    //key是数据库中的字段名
    //value是显示时呈现的栏目名称
    data_schema_convert: {
      exam_site_code: '考点',
      name: '姓名',
      sex: '性别',
      birthday: '出生日期',
      id_type: '证件类型',
      id_number: '证件号码',
      nationality: '民族',
      career: '职业',
      degree_of_education: '文化程度',
      training_type: '培训类型',
      subject_code: '考试科目',
      post_code: '邮政编码',
      address: '地址',
      email: '电子邮箱',
      phone: '联系电话',
      remark:'备注'
    }
  }
})();
