CREATE TABLE `data` (
	`exam_site_code` INT(11) NOT NULL,
	`subject_code` TINYINT(4) NOT NULL,
	`name` VARCHAR(255) NOT NULL,
	`sex` VARCHAR(6) NOT NULL,
	`birthday` VARCHAR(255) NOT NULL,
	`id_type` TINYINT(4) NOT NULL,
	`id_number` VARCHAR(255) NOT NULL,
	`nationality` TINYINT(4) NOT NULL,
	`career` TINYINT(4) NOT NULL,
	`degree_of_education` TINYINT(4) NOT NULL,
	`training_type` TINYINT(4) NOT NULL,
	`post_code` VARCHAR(11) NULL DEFAULT NULL,
	`address` VARCHAR(255) NULL DEFAULT NULL,
	`email` VARCHAR(255) NOT NULL DEFAULT NULL,
	`phone` VARCHAR(11) NULL DEFAULT NULL,
	`remark` VARCHAR(255) NULL DEFAULT NULL,
	`create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
	`latest_revise_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`revise_count` INT(11) NULL DEFAULT '0',
	PRIMARY KEY (`id_number`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;
